product: amazonlinux2
full_name: Amazonlinux 2
type: platform

benchmark_id: AL-2
benchmark_root: "../../linux_os/guide"
components_root: "../../components"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "systemd"

cpes_root: "../../shared/applicability"
cpes:
  - amazonlinux2:
      name: "cpe:/o:amazonlinux:2"
      title: "Amazonlinux 2"
      check_id: installed_OS_is_amazonlinux2

reference_uris:
  cis: 'https://www.cisecurity.org/benchmark/amazon_linux/'
