product: al2
full_name: Amazon Linux 2
type: platform

benchmark_id: AL-2
benchmark_root: "../../linux_os/guide"
components_root: "../../components"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "systemd"

cpes_root: "../../shared/applicability"
cpes:
  - al2:
      name: "cpe:/o:amazon:amazon_linux:2"
      title: "Amazon Linux 2"
      check_id: installed_OS_is_al2

reference_uris:
  cis: 'https://www.cisecurity.org/benchmark/amazon_linux/'
